apiVersion: apps/v1
kind: Deployment
metadata:
  name: lldap
  labels:
    app.kubernetes.io/name: lldap

spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: lldap
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: lldap
    spec:
      containers:
      - name: lldap
        image: lldap/lldap:v0.5.0
        ports:
          - containerPort: 3890
          - containerPort: 6360
          - containerPort: 17170
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 500Mi
        env:
        - name: UID
          value: "1000"
        - name: GID
          value: "1000"
        - name: LLDAP_LDAP_BASE_DN
          value: "dc=example,dc=com"
        - name: LLDAP_LDAPS_OPTIONS__ENABLED
          value: "false"
