apiVersion: v1
kind: Service
metadata:
  name: lldap-ui
  labels:
    app.kubernetes.io/name: lldap
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 17170
  selector:
    app.kubernetes.io/name: lldap
